export const bootSequenceLines = [
  '      ___           ___           ___           ___                       ___           ___           ___           ___           ___           ___     ',
  '     /\\  \\         /\\  \\         /\\  \\         /\\__\\          ___        /\\__\\         /\\  \\         /\\  \\         /\\  \\         /\\  \\         /\\  \\    ',
  '    /::\\  \\       /::\\  \\       /::\\  \\       /:/  /         /\\  \\      /:/ _/_       /::\\  \\       /::\\  \\       /::\\  \\       /::\\  \\       /::\\  \\   ',
  '   /:/\\:\\  \\     /:/\\:\\  \\     /:/\\:\\  \\     /:/__/          \\:\\  \\    /:/ /:/ __\\     /:/\\:\\  \\     /:/\\:\\  \\     /:/\\:\\  \\     /:/\\:\\  \\     /:/\\ \\  \\  ',
  '  /::\\~\\:\\  \\   /::\\~\\:\\  \\   /:/  \\:\\  \\   /::\\  \\ ___      /::\\__\\  /:/ /:/ _/_   /::\\~\\:\\  \\   /::\\~\\:\\  \\   /::\\~\\:\\  \\   /:/  \\:\\  \\   _\\:\\~\\ \\  \\ ',
  ' /:/\\:\\ \\:\\__\\ /:/\\:\\ \\:\\__\\ /:/__/ \\:\\__\\ /:/\\:\\  /\\__\\  __/:/\\/__/ /:/_/:/ /\\__\\ /:/\\:\\ \\:\\__\\ /:/\\:\\ \\:\\__\\ /:/\\:\\ \\:\\__\\ /:/__/ \\:\\__\\ /\\ \\:\\ \\ \\__\\',
  ' \\/__\\:\\/:/  / \\/_|::\\/:/  / \\:\\  \\  \\/__/ \\/__\\:\\/:/  / /\\/:/  /    \\:\\/:/ /:/  / \\/__\\:\\/:/  / \\/_|::\\/:/  / \\:\\~\\:\\ \\/__/ \\:\\  \\ /:/  / \\:\\ \\:\\ \\/__/',
  '      \\::/  /     |:|::/  /   \\:\\  \\            \\::/  /  \\::/__/      \\::/_/:/  /       \\::/  /     |:|::/  /   \\:\\ \\:\\__\\    \\:\\  /:/  /   \\:\\ \\:\\__\\  ',
  '      /:/  /      |:|\\/__/     \\:\\  \\           /:/  /    \\:\\__\\       \\:\\/:/  /        /:/  /      |:|\\/__/     \\:\\ \\/__/     \\:\\/:/  /     \\:\\/:/  /  ',
  '     /:/  /       |:|  |        \\:\\__\\         /:/  /      \\/__/        \\::/  /        /:/  /       |:|  |        \\:\\__\\        \\::/  /       \\::/  /   ',
  '     \\/__/         \\|__|         \\/__/         \\/__/                     \\/__/         \\/__/         \\|__|         \\/__/         \\/__/         \\/__/    ',
  'Starting LSB: daemon to balance interrupts for SMP systems...',
  '[ OK ] Started ACPI event daemon.',
  'Starting LSB: Set the CPU Frequency Scaling governor to "ondemand"...',
  'Starting Avahi mDNS/DNS-SD Stack...',
  'Starting LSB: Record successful boot for GRUB...',
  'Starting Modem Manager...',
  '[ OK ] Started ClamAV virus database updater.',
  'Starting LSB: Speech Dispatcher...',
  'Starting Accounts Service...',
  'Starting Permit User Sessions...',
  '[ OK ] Started Run anacron jobs.',
  'Starting Save/Restore Sound Card State...',
  'Starting Thermal Daemon Service...',
  '[ OK ] Started CUPS Scheduler.',
  'Starting LSB: automatic crash report generation...',
  'Starting Restore /etc/resolv.conf if the system crashed before the ppp link was shut down...',
  'Starting Snappy daemon...',
  '[ OK ] Started Regular background program processing daemon.',
  '[ OK ] Started D-Bus System Message Bus.',
  'Starting Network Manager...',
  '[ OK ] Started Detect the available GPUs and deal with any system changes.',
  '[ OK ] Started Permit User Sessions.',
  '[ OK ] Started Restore /etc/resolv.conf if the system crashed before the ppp link was shut down.',
  '[ OK ] Started Save/Restore Sound Card State.',
  '[ OK ] Started LSB: Set the CPU Frequency Scaling governor to "ondemand".',
  '[ OK ] Started LSB: Speech Dispatcher.',
  'Starting Light Display Manager...',
  '[ OK ] Started Login Service.',
  '[ OK ] Started LSB: automatic crash report generation.',
  '[ OK ] Started System Logging Service.',
  '[ OK ] Started LSB: daemon to balance interrupts for SMP systems.',
  '[ OK ] Started Avahi mDNS/DNS-SD Stack.',
  '[ OK ] Started Make remote CUPS printers available locally.',
  '[ OK ] Started Thermal Daemon Service.',
  '[ OK ] Started Light Display Manager.',
  'Starting Authenticate and Authorize Users to Run Privileged Tasks...',
  '[ OK ] Started Authenticate and Authorize Users to Run Privileged Tasks.',
  '[ OK ] Started LSB: Record successful boot for GRUB.',
  '[ OK ] Started Modem Manager.',
  '[ OK ] Started Network Manager.',
  '[ OK ] Reached target Network.',
  '[ OK ] Started Unattended Upgrades Shutdown.',
  'Starting Network Manager Wait Online...',
  'Starting Network Manager Script Dispatcher Service...',
  '[ OK ] Started Network Manager Script Dispatcher Service.',
  'Starting Hostname Service...',
  '[ OK ] Started Hostname Service.'
];
