export const bootSequenceLines = [
  "       _       _______      ______  ____  ____  _____  ____      ____  _       _______     ________     ___     ______   ",
  "     / \\     |_   __ \\   .' ___  ||_   ||   _||_   _||_  _|    |_  _|/ \\     |_   __ \\   |_   __  |  .'   `. .' ____ \\  ",
  "    / _ \\      | |__) | / .'   \\_|  | |__| |    | |    \\ \\/  /\\  / / / _ \\      | |__) |    | |_ \\_| /  .-.  \\| (___ \\_| ",
  "   / ___ \\     |  __ /  | |         |  __  |    | |     \\ \\/  \\/ / / ___ \\     |  __ /     |  _| _  | |   | | _.____`.  ",
  " _/ /   \\ \\_  _| |  \\ \\_\\ _.___.'\\ _| |  | |_  _| |_     \\  /\\  /_/ /   \\ \\_  _| |  \\ \\_  _| |__/ | \\  `-'  /| \\____) | ",
  " |____| |____||____| |___|`.____ .'|____||____||_____|     \\/  \\/|____| |____||____| |___||________|  `.___.'  \\______.' ",
  "                                                                                                                        ",
  "Starting LSB: daemon to balance interrupts for SMP systems...",
  '[ OK ] Started ACPI event daemon.',
  'Starting LSB: Set the CPU Frequency Scaling governor to "ondemand"...',
  'Starting Avahi mDNS/DNS-SD Stack...',
  'Starting LSB: Record successful boot for GRUB...',
  'Starting Modem Manager...',
  '[ OK ] Started ClamAV virus database updater.',
  'Starting LSB: Speech Dispatcher...',
  'Starting Accounts Service...',
  'Starting Permit User Sessions...',
  '[ OK ] Started Run anacron jobs.',
  'Starting Save/Restore Sound Card State...',
  'Starting Thermal Daemon Service...',
  '[ OK ] Started CUPS Scheduler.',
  'Starting LSB: automatic crash report generation...',
  'Starting Restore /etc/resolv.conf if the system crashed before the ppp link was shut down...',
  'Starting Snappy daemon...',
  '[ OK ] Started Regular background program processing daemon.',
  '[ OK ] Started D-Bus System Message Bus.',
  'Starting Network Manager...',
  '[ OK ] Started Detect the available GPUs and deal with any system changes.',
  '[ OK ] Started Permit User Sessions.',
  '[ OK ] Started Restore /etc/resolv.conf if the system crashed before the ppp link was shut down.',
  '[ OK ] Started Save/Restore Sound Card State.',
  '[ OK ] Started LSB: Set the CPU Frequency Scaling governor to "ondemand".',
  '[ OK ] Started LSB: Speech Dispatcher.',
  'Starting Light Display Manager...',
  '[ OK ] Started Login Service.',
  '[ OK ] Started LSB: automatic crash report generation.',
  '[ OK ] Started System Logging Service.',
  '[ OK ] Started LSB: daemon to balance interrupts for SMP systems.',
  '[ OK ] Started Avahi mDNS/DNS-SD Stack.',
  '[ OK ] Started Make remote CUPS printers available locally.',
  '[ OK ] Started Thermal Daemon Service.',
  '[ OK ] Started Light Display Manager.',
  'Starting Authenticate and Authorize Users to Run Privileged Tasks...',
  '[ OK ] Started Authenticate and Authorize Users to Run Privileged Tasks.',
  '[ OK ] Started LSB: Record successful boot for GRUB.',
  '[ OK ] Started Modem Manager.',
  '[ OK ] Started Network Manager.',
  '[ OK ] Reached target Network.',
  '[ OK ] Started Unattended Upgrades Shutdown.',
  'Starting Network Manager Wait Online...',
  'Starting Network Manager Script Dispatcher Service...',
  '[ OK ] Started Network Manager Script Dispatcher Service.',
  'Starting Hostname Service...',
  '[ OK ] Started Hostname Service.',
  '[ OK ] Started Network Manager Wait Online.',
  '[ OK ] Reached target Network is Online.',
  'Starting LSB: VirtualBox Linux kernel modules...',
  'Starting LSB: Network Technologies daemon...',
  '[ OK ] Started LSB: VirtualBox Linux kernel modules.',
  'Starting OpenSSH server daemon...',
  '[ OK ] Started OpenSSH server daemon.',
  'Starting Network Time Synchronization...',
  '[ OK ] Started Network Time Synchronization.',
  '[ OK ] Reached target System Time Synchronized.',
  'Starting Postfix Mail Transport Agent...',
  '[ OK ] Started Postfix Mail Transport Agent.',
  'Starting Samba SMB Daemon...',
  'Starting Samba NMB Daemon...',
  '[ OK ] Started Samba NMB Daemon.',
  '[ OK ] Started Samba SMB Daemon.',
  'Starting Bluetooth service...',
  '[ OK ] Started Bluetooth service.',
  '[ OK ] Reached target Bluetooth.',
  'Starting Disk Manager Daemon...',
  '[ OK ] Started Disk Manager Daemon.',
  'Starting User Manager for UID 121...',
  '[ OK ] Started User Manager for UID 121.',
  'Starting GNOME Display Manager Session Worker for UID 121...',
  '[ OK ] Started GNOME Display Manager Session Worker for UID 121.',
  'Starting Virtual File System Service...',
  '[ OK ] Started Virtual File System Service.',
  'Starting Sound Service...',
  '[ OK ] Started Sound Service.',
  'Starting RealtimeKit Scheduling Policy Service...',
  '[ OK ] Started RealtimeKit Scheduling Policy Service.',
  'Starting Power Management Daemon...',
  '[ OK ] Started Power Management Daemon.',
  'Starting Screen Saver and Locker Service...',
  '[ OK ] Started Screen Saver and Locker Service.',
  'Starting Accessibility Bus Listener...',
  '[ OK ] Started Accessibility Bus Listener.',
  'Starting X11 VNC Server...',
  '[ OK ] Started X11 VNC Server.',
  'Starting PulseAudio Sound System...',
  '[ OK ] Started PulseAudio Sound System.',
  'Starting Snap Daemon Application Activation Helper...',
  '[ OK ] Started Snap Daemon Application Activation Helper.',
  'Starting Periodic Command Scheduler...',
  '[ OK ] Started Periodic Command Scheduler.',
  'Starting Mount network filesystems...',
  '[ OK ] Started Mount network filesystems.',
  'Starting CUPS Web Interface daemon...',
  '[ OK ] Started CUPS Web Interface daemon.',
  'Starting MariaDB 10.6 database server...',
  '[ OK ] Started MariaDB 10.6 database server.',
  'Starting Apache2 Web Server...',
  '[ OK ] Started Apache2 Web Server.',
  'Starting Docker Application Container Engine...',
  '[ OK ] Started Docker Application Container Engine.',
  'Starting Containerd container runtime...',
  '[ OK ] Started Containerd container runtime.',
  'Starting Fail2Ban Service...',
  '[ OK ] Started Fail2Ban Service.',
  'Starting FirewallD - dynamic firewall daemon...',
  '[ OK ] Started FirewallD - dynamic firewall daemon.',
  'Starting Uncomplicated Firewall...',
  '[ OK ] Started Uncomplicated Firewall.',
  'Starting UFW transient rules engine...',
  '[ OK ] Started UFW transient rules engine.',
  'Starting Kernel Logging Service...',
  '[ OK ] Started Kernel Logging Service.',
  'Starting Anonymizing overlay network for TCP...',
  '[ OK ] Started Anonymizing overlay network for TCP.',
  'Starting Advanced Linux Sound Architecture (ALSA) Mixer settings...',
  '[ OK ] Started Advanced Linux Sound Architecture (ALSA) Mixer settings.',
  'Starting Load/Save RF Kill Switch Status...',
  '[ OK ] Started Load/Save RF Kill Switch Status.',
  'Starting Hardware Performance Monitoring Sampler...',
  '[ OK ] Started Hardware Performance Monitoring Sampler.',
  'Starting Package Kit Daemon...',
  '[ OK ] Started Package Kit Daemon.',
  'Starting Polkit Action Authority...',
  '[ OK ] Started Polkit Action Authority.',
  'Starting Smartcard Daemon...',
  '[ OK ] Started Smartcard Daemon.',
  'Starting Tool to automatically collect crash data...',
  '[ OK ] Started Tool to automatically collect crash data.',
  'Starting Manage Sound Card State (alsa-utils)...',
  '[ OK ] Started Manage Sound Card State (alsa-utils).',
  'Starting System Security Services Daemon...',
  '[ OK ] Started System Security Services Daemon.',
  'Starting Name Service Cache Daemon...',
  '[ OK ] Started Name Service Cache Daemon.',
  'Starting Login to default iSCSI targets...',
  '[ OK ] Started Login to default iSCSI targets.',
  'Starting Hardware abstraction layer...',
  '[ OK ] Started Hardware abstraction layer.',
  'Starting D-Bus User Message Bus...',
  '[ OK ] Started D-Bus User Message Bus.',
  'Starting Flatpak Document Portal...',
  '[ OK ] Started Flatpak Document Portal.',
  'Starting Flatpak Permission Store...',
  '[ OK ] Started Flatpak Permission Store.',
  'Starting GIO URL Monitor daemon...',
  '[ OK ] Started GIO URL Monitor daemon.',
  'Starting Evolution Address Book Service...',
  '[ OK ] Started Evolution Address Book Service.',
  'Starting Evolution Calendar Service...',
  '[ OK ] Started Evolution Calendar Service.',
  'Starting Evolution Source Registry...',
  '[ OK ] Started Evolution Source Registry.',
  'Starting GNOME Keyring Daemon: Secret Service...',
  '[ OK ] Started GNOME Keyring Daemon: Secret Service.',
  'Starting GNOME Keyring Daemon: SSH Agent...',
  '[ OK ] Started GNOME Keyring Daemon: SSH Agent.',
  'Starting GNOME Keyring Daemon: PKCS#11 Component...',
  '[ OK ] Started GNOME Keyring Daemon: PKCS#11 Component.',
  'Starting Tracker metadata database store and indexer...',
  '[ OK ] Started Tracker metadata database store and indexer.',
  'Starting Virtual Console Setup...',
  '[ OK ] Started Virtual Console Setup.',
  'Starting Tell Plymouth To Write Out Runtime Data...',
  '[ OK ] Started Tell Plymouth To Write Out Runtime Data.',
  'Starting Dispatcher daemon for systemd-networkd...',
  '[ OK ] Started Dispatcher daemon for systemd-networkd.',
  'Starting Daily Cleanup of Temporary Directories...',
  '[ OK ] Started Daily Cleanup of Temporary Directories.',
  'Starting Discard unused blocks on filesystems...',
  '[ OK ] Started Discard unused blocks on filesystems.',
  'Starting Daily apt download activities...',
  '[ OK ] Started Daily apt download activities.',
  'Starting Daily apt upgrade and clean activities...',
  '[ OK ] Started Daily apt upgrade and clean activities.',
  'Starting Update man-db cache...',
  '[ OK ] Started Update man-db cache.',
  'Starting Rotate log files...',
  '[ OK ] Started Rotate log files.',
  'Starting Backup of /etc directory...',
  '[ OK ] Started Backup of /etc directory.',
  'Starting Clean php session files...',
  '[ OK ] Started Clean php session files.',
  'Starting Complain if a reboot is needed...',
  '[ OK ] Started Complain if a reboot is needed.',
  'Starting Message of the Day update...',
  '[ OK ] Started Message of the Day update.',
  'Starting Check for newer hardware enablement stack...',
  '[ OK ] Started Check for newer hardware enablement stack.',
  'Starting Generate security settings for User...',
  '[ OK ] Started Generate security settings for User.',
  'Starting Dynamic Device Management Daemon...',
  '[ OK ] Started Dynamic Device Management Daemon.',
  'Starting Monitor for thermal events...',
  '[ OK ] Started Monitor for thermal events.',
  'Starting Monitor for ACPI events...',
  '[ OK ] Started Monitor for ACPI events.',
  'Starting Session 1 of user admin...',
  '[ OK ] Started Session 1 of user admin.',
  'Starting User Manager for UID 1000...',
  '[ OK ] Started User Manager for UID 1000.',
  'Starting D-Bus User Message Bus for UID 1000...',
  '[ OK ] Started D-Bus User Message Bus for UID 1000.',
  'Starting Virtual File System Service for UID 1000...',
  '[ OK ] Started Virtual File System Service for UID 1000.',
  'Starting GNOME Terminal Server...',
  '[ OK ] Started GNOME Terminal Server.',
  'Starting Desktop accessibility framework...',
  '[ OK ] Started Desktop accessibility framework.',
  'Starting PipeWire Multimedia Service...',
  '[ OK ] Started PipeWire Multimedia Service.',
  'Starting PipeWire Media Session Manager...',
  '[ OK ] Started PipeWire Media Session Manager.',
  'Starting WirePlumber audio topology manager...',
  '[ OK ] Started WirePlumber audio topology manager.',
  'Starting PipeWire PulseAudio Emulation...',
  '[ OK ] Started PipeWire PulseAudio Emulation.',
  'Starting Notification Daemon...',
  '[ OK ] Started Notification Daemon.',
  'Starting Network Manager Applet...',
  '[ OK ] Started Network Manager Applet.',
  'Starting Power Manager Applet...',
  '[ OK ] Started Power Manager Applet.',
  'Starting Bluetooth Applet...',
  '[ OK ] Started Bluetooth Applet.',
  'Starting SSH Key Agent Frontend...',
  '[ OK ] Started SSH Key Agent Frontend.',
  'Starting Evolution Alarm Notify...',
  '[ OK ] Started Evolution Alarm Notify.',
  'Starting Spice VDAgent Core Daemon...',
  '[ OK ] Started Spice VDAgent Core Daemon.',
  'Starting XDG Desktop Portal Service...',
  '[ OK ] Started XDG Desktop Portal Service.',
  'Starting XDG Desktop Portal GTK frontend...',
  '[ OK ] Started XDG Desktop Portal GTK frontend.',
  'Starting GNOME Settings Daemon...',
  '[ OK ] Started GNOME Settings Daemon.',
  'Starting GNOME Color Management Daemon...',
  '[ OK ] Started GNOME Color Management Daemon.',
  'Starting GNOME Date & Time Daemon...',
  '[ OK ] Started GNOME Date & Time Daemon.',
  'Starting GNOME Housekeeping Daemon...',
  '[ OK ] Started GNOME Housekeeping Daemon.',
  'Starting GNOME Keyboard Daemon...',
  '[ OK ] Started GNOME Keyboard Daemon.',
  'Starting GNOME Media Keys Daemon...',
  '[ OK ] Started GNOME Media Keys Daemon.',
  'Starting GNOME Power Daemon...',
  '[ OK ] Started GNOME Power Daemon.',
  'Starting GNOME Print Notifications Daemon...',
  '[ OK ] Started GNOME Print Notifications Daemon.',
  'Starting GNOME Remote Desktop Daemon...',
  '[ OK ] Started GNOME Remote Desktop Daemon.',
  'Starting GNOME RFKill Daemon...',
  '[ OK ] Started GNOME RFKill Daemon.',
  'Starting GNOME Screensaver Daemon...',
  '[ OK ] Started GNOME Screensaver Daemon.',
  'Starting GNOME Sharing Daemon...',
  '[ OK ] Started GNOME Sharing Daemon.',
  'Starting GNOME Smartcard Daemon...',
  '[ OK ] Started GNOME Smartcard Daemon.',
  'Starting GNOME Sound Daemon...',
  '[ OK ] Started GNOME Sound Daemon.',
  'Starting GNOME Wacom Daemon...',
  '[ OK ] Started GNOME Wacom Daemon.',
  'Starting GNOME XSettings Daemon...',
  '[ OK ] Started GNOME XSettings Daemon.',
  'Starting Window Manager...',
  '[ OK ] Started Window Manager.',
  'Starting GNOME Shell Desktop Environment...',
  '[ OK ] Started GNOME Shell Desktop Environment.',
  '[ OK ] Reached target Graphical Interface.',
  '[ OK ] Reached target Multi-User System.',
  '[ OK ] Reached target Graphical User Interface.',
  'Starting Update UTMP about System Runlevel Changes...',
  '[ OK ] Started Update UTMP about System Runlevel Changes.',
  'Starting Startup finishing notification...',
  '[ OK ] Started Startup finishing notification.',
  'Linux version 6.8.0-generic (gcc version 13.2.0)',
  'System boot process successfully completed.',
  'Thank you for using Archiware OS. <3'
];
